name = "KorzyńskiSpin"
uuid = "dddeb715-7fc8-4947-8935-98683755b697"
authors = ["Erik Schnetter <schnetter@gmail.com>"]
version = "1.0.0"

[deps]
AbstractSphericalHarmonics = "ee470b23-2871-4f3a-b920-8523874a9e46"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
FastSphericalHarmonics = "d335c211-7587-445e-a753-f0b1fb7e445f"

[sources]
AbstractSphericalHarmonics = {path = "../AbstractSphericalHarmonics.jl"}

[compat]
FastSphericalHarmonics = "1.3"
SpacetimeMetrics = "1.5"
StaticArrays = "1"
julia = "1.11"

[extras]
AbstractSphericalHarmonics = "ee470b23-2871-4f3a-b920-8523874a9e46"
SpacetimeMetrics = "77e61b41-605e-43a6-b70f-04b7dcd1f572"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SpacetimeMetrics", "AbstractSphericalHarmonics"]
